### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by pcfreak30** [Automattic/wp-super-cache#128]
The plugin should be reformatted to wordpress standards. Considering this is authored by Automattic im surprised this isn't more enforced.

**Comment by kraftbj** [comment]
Generally, WordPress's coding standards include not refactoring for the sake of refactoring ( https://make.wordpress.org/core/handbook/contribute/code-refactoring/ ). When changes are made, the sections of the code impacted should be brought up to date.

If/when a more wholesale change to the functionality to the code is made, something more pronounced would be done.

I'm going to close this since it won't be something we tackle in and of itself, but in the course of working on other issues.
