### ISSUE TITLE
Feature-Request: Allow for editing Cache-Control header

### ISSUE THREAD

**Issue by sanojb** [Automattic/wp-super-cache#154]
The Cache-Control header is currently hard-coded to "max-age=3, must-revalidate". Not everybody might want to request the browser to invalidate the resource after only 3 seconds. It would be nice to have the option of changing this in the settings.

**Comment by Sophist-UK** [comment]
I would agree that 3 seconds is a bit short.

If you are using an apache web server, have you tried using .htaccess to override this.

**Comment by sanojb** [comment]
Well, I simply changed it in the code. This is not such a good idea if an update comes in, but it works for now. The reason I created the feature request is because the user should be able to edit such an important value from the admin panel.

**Comment by kporembinski** [comment]
It will be good to implement this.

**Comment by jayhybrid** [comment]
I also think this is a great idea. I am trying to avoid manually writting the htaccess file and editing the plugins code. Also I do not want to install yet another plugin, because most of the cache control plugins also are a caching plugin and it feels like an overkill to me.

**Comment by BrookeDot** [comment]
I'm closing this as fixed in #555. One can now define `WPSC_CACHE_CONTROL_HEADER` to control the `max-age`. For example:

 `define( 'WPSC_CACHE_CONTROL_HEADER', 'max-age=3600, must-revalidate' );`

Note, you will need to flush the cache for the change to take effect. The source for this functionality can be found here:
https://github.com/Automattic/wp-super-cache/blob/master/wp-cache-phase2.php#L160
