### ISSUE TITLE
'DONOTCACHEPAGE' constant no working as expected

### ISSUE THREAD

**Issue by amcfarlane** [Automattic/wp-super-cache#189]
Apologies, this is my first time posting a public GitHub issue, so excuse me if this is incorrect or my etiquette is off. Though looking at the source code I suspect that the 'DONOTCACHEPAGE' constant isn't working as expected.

I am trying to add my own logic to stop caching completely when a user is logged into my website, this uses a 3rd party cookie. So I have added the following to the wp-config.php file. I tried functions.php initially, but this is called after the WP Super Cache plugin (any advice on the location of this would be appreciated also).

```
if( isset( $_COOKIE['LoggedInCookie'] ) ){
	define( 'DONOTCACHEPAGE', 1 );
}
```

The above does not disable caching as expected when the cookie is set. I think this is due to the page already being cached when the user is logged out. I would expect define( 'DONOTCACHEPAGE', 1 ) to stop the page being cached.

If I use the following, it works as expected.

```
if( isset( $_COOKIE['LoggedInCookie'] ) ){
	$_GET['donotcachepage'] = '{secret}';
}
```

It looks like the later sets '$cache_enabled = false;' in 'wp-cache-phase1.php' which I would imagine would be the expected behaviour of defining define( 'DONOTCACHEPAGE', 1 ) by itself in the first instance.

**Comment by donnchawp** [comment]
This probably belongs on the WP Super Cache support forum, but look for "Don’t cache pages for known users." in the advanced settings page.

The DONOTCACHEPAGE constant does work correctly. It stops the page being cached but if it's already cached the cached page will be served to the user.

The behaviour of setting that constant vs using the secret key is different, and unintentional, but I don't think we should change it because they have been like that for several years now.
