### ISSUE TITLE
New wp super cache problem= mobile cache, compress (zip) don't working

### ISSUE THREAD

**Issue by kuaza61** [Automattic/wp-super-cache#300]
im update new wp super cache but very problem :/ don't working mobile detection, yes caching but im open my website in deskop, im see mobile cache :/

thanks for help.

**Comment by donnchawp** [comment]
Thanks for the report. Can you disable mobile device support to avoid the problem?

**Comment by kuaza61** [comment]
Back to the old version, because 90% of my visitors mobile. I am waiting for your solution. Thanks.

**Comment by kuaza61** [comment]
im update 1.5.1 and im disabled "Cache HTTP headers with page content." after good working mobile and deskop cache. but when i select "Cache HTTP headers with page content." after interfere mobile cache or deskop cache.

Thanks.

**Comment by donnchawp** [comment]
Thanks for the screenshot. I understand that English isn't your first language, so I'm extra grateful for the report.

So, does this only happens if the following are true?
1. "Cache HTTP headers" is enabled.
2. "Mobile Browser support" is enabled.

I think I know why too. The "key" used to find the right cache file if the HTTP headers are cached doesn't include the browser user agent for obvious reasons, but it should include mobile browser status if that's enabled.

**Comment by donnchawp** [comment]
Can you try the code I added in #308? It's a one line change to wp-cache-phase1.php and it should fix the problem for you.

**Comment by kuaza61** [comment]
Thank you very much <3
