### ISSUE TITLE
Site map breaks when user not logged in

### ISSUE THREAD

**Issue by amitmalewar** [Automattic/wp-super-cache#325]
I am using sitemap by Yoast SEO. Using WP Super cache plugin breaks sitemap when the administrator is not logged in. 
Sitemap works well when the administrator is logged in to the dashboard.

**Comment by donnchawp** [comment]
How does it break? Do you mean you can load the sitemap if you're logged in, but can't if you're logged out?
Did you find any errors in your PHP error_log? Or did you enable debugging and check what the debug log said when you tried to load the sitemap as a logged out user?

**Comment by amitmalewar** [comment]
Sitemap loads in both conditions. 
When Logged in http://prntscr.com/g2hksz
Without logged in: http://prntscr.com/g2hkg9

there are no errors in PHP error_log file

**Comment by donnchawp** [comment]
OK, the content-type returned by that URL is `content-type:text/html; charset="UTF-8"` which is wrong.

Have you tried disabling caching of feeds on the Advanced settings page?

The problem is that Yoast's plugin needs to tell Supercache that the URL is a sitemap in the same way that [Jetpack now does this](https://github.com/Automattic/jetpack/pull/7397). If I have time I'll submit a patch to them adding that feature.

**Comment by amitmalewar** [comment]
As a temporary fix, I have added following to the Add here strings (not a filename) that forces a page not to be cached in ADVANCED setting section.

```
sitemap(_index)?\.xml(\.gz)?
([a-z0-9_\-]+)?sitemap\.xsl
[a-z0-9_\-]+-sitemap([0-9]+)?\.xml(\.gz)?
```

**Comment by donnchawp** [comment]
@amitmalewar - can you try the code in #346 please? That should fix the problem but needs testing.

**Comment by stodorovic** [comment]
If it helps, detection of sitemaps (Yoast SEO) is possible with: ` if ( get_query_var( 'sitemap' ) || get_query_var( 'xsl' ) ) `. Google XML Sitemaps Generator for WordPress - `get_query_var( "xml_sitemap" )`. So, it should be added before is_feed - https://github.com/Automattic/wp-super-cache/blob/master/wp-cache-phase2.php#L1119

I've some contribution related to Yoast SEO sitemaps, so I'll try to help.

Second issue. When wp-super-cache uses rewrite rules:
```
[...]$ ls -al post-sitemap.xml/
-rw-r--r--  1  1601 Aug 15 16:13 index.html
-rw-r--r--  1   567 Aug 15 16:13 index.html.gz
```
Because these files are `html` and `html.gz` (see rule in .htaccess), apache serves them as `text/html`. So, possible workaround  should be using `index.xml` and `index.xml.gz` for XML files. I know that isn't easy to change everything, but it's only way to improve caching.

**Comment by donnchawp** [comment]
It's odd you're seeing index.html and index.html.gz in that directory. They should be WP-Cache files which includes a meta file containing the content type. Let's continue the conversation on #346.
