### ISSUE TITLE
json_encode(): Invalid UTF-8 sequence in argument in /wp-cache-phase2.php on line 53

### ISSUE THREAD

**Issue by f2ex** [Automattic/wp-super-cache#349]
I found some unusual browsing behavior, I'm not sure if this is not an attack, but these behaviors seem to have caused some mistakes

2017/08/19 07:56:15 [error] 21178#0: *8407 FastCGI sent in stderr: "PHP message: PHP Warning:  json_encode(): Invalid UTF-8 sequence in argument in /XXXX.com/wp-content/plugins/wp-super-cache/**wp-cache-phase2.php on line 53**
PHP message: WordPress数据库查询SELECT SQL_CALC_FOUND_ROWS  wp_posts.ID FROM wp_posts  WHERE 1=1  AND (((wp_posts.post_title LIKE '%?????o?��?��?a???%') OR (wp_posts.post_excerpt LIKE '%?????o?��?��?a???%') OR (wp_posts.post_content LIKE '%?????o?��?��?a???%')))  AND (wp_posts.post_password = '')  AND wp_posts.post_type IN ('post', 'page', 'attachment') AND (wp_posts.post_status = 'publish')  ORDER BY wp_posts.post_title LIKE '%?????o?��?��?a???%' DESC, wp_posts.post_date DESC LIMIT 0, 18时发生Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8mb4_unicode_520_ci,COERCIBLE) for operation 'like'错误，这是由require('wp-blog-header.php'), wp, WP->main, WP->query_posts, WP_Query->query, WP_Query->get_posts查询的。" while reading response header from upstream, client: 58.211.2.66, server: XXXX.com, request: "GET /?s=?????o?��?��?a??? HTTP/1.1", upstream: "fastcgi://unix:/dev/shm/php-cgi.sock:", host: "www.XXXX.com", referrer: "http://www.XXXX.com/category/html/"

2017/08/19 07:56:23 [error] 21179#0: *8412 FastCGI sent in stderr: "PHP message: PHP Warning:  json_encode(): Invalid UTF-8 sequence in argument in /XXXX.com/wp-content/plugins/wp-super-cache/**wp-cache-phase2.php on line 53**
PHP message: WordPress数据库查询SELECT SQL_CALC_FOUND_ROWS  wp_posts.ID FROM wp_posts  WHERE 1=1  AND (((wp_posts.post_title LIKE '%?��?��?a???%') OR (wp_posts.post_excerpt LIKE '%?��?��?a???%') OR (wp_posts.post_content LIKE '%?��?��?a???%')))  AND (wp_posts.post_password = '')  AND wp_posts.post_type IN ('post', 'page', 'attachment') AND (wp_posts.post_status = 'publish')  ORDER BY wp_posts.post_title LIKE '%?��?��?a???%' DESC, wp_posts.post_date DESC LIMIT 0, 18时发生Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8mb4_unicode_520_ci,COERCIBLE) for operation 'like'错误，这是由require('wp-blog-header.php'), wp, WP->main, WP->query_posts, WP_Query->query, WP_Query->get_posts查询的。" while reading response header from upstream, client: 58.211.2.36, server: XXXX.com, request: "GET /?s=?��?��?a??? HTTP/1.1", upstream: "fastcgi://unix:/dev/shm/php-cgi.sock:", host: "www.XXXX.com", referrer: "http://www.XXXX.com/?s=%E6%89%8B%E6%9C%BA%E5%AF%BC%E8%88%AA%E6%9D%A1"

**Comment by donnchawp** [comment]
Interesting. Doing a Google search for "json_encode(): Invalid UTF-8 sequence in argument" brings up lots of results. Did this cause a fatal error? Line 53 is only a wp_cache_debug() call to do logging so it's not critical to the plugin. If this is just a warning you can ignore it until we get it fixed.

[This page](https://stackoverflow.com/questions/279170/utf-8-all-the-way-through) suggests ways to avoid the problem. It's because json_encode() needs valid UTF-8 data as input according to [another SA answer](https://stackoverflow.com/a/33000390).

**Comment by f2ex** [comment]
@donnchawp Thank you very much that this is not a fatal error ,  the first time I found this error in wordpress 4.8.1 .  I am trying to use some solutions .

**Comment by stodorovic** [comment]
I was able to reproduce this PHP Warning. If someone sends GET request with garbled characters (uses iso-8859-1 instead of utf-8), then it's possible that [json_encode](http://php.net/manual/en/function.json-encode.php) can't handle it and php reports warning (it's only logged into error_log ).

Since WP 4.10, there is function [wp_json_encode](https://developer.wordpress.org/reference/functions/wp_json_encode/) which replaces invalid characters with `?`. I tested and it works without PHP warning. So, I created function `wpsc_dump_get_request` (part of #384) to get rid of this warning.

PHP example which triggers warning:
```php
<?php

error_reporting(E_ALL);
ini_set( 'display_errors', 0 );
ini_set( 'log_errors', 1 );
ini_set( 'error_log', 'php-error.log' );

$_GET[ 's' ] = quoted_printable_decode( '=B0' );

echo json_encode( $_GET );
```

Error log:
`[14-Sep-2017 09:01:23] PHP Warning:  json_encode(): Invalid UTF-8 sequence in argument in .../test.php on line 10`

@f2ex Second PHP warning is related to non-sanitazed search string. There are instructions how to handle it:
https://codex.wordpress.org/Validating_Sanitizing_and_Escaping_User_Data

You should sanitize search string before MySQL query (using function [sanitize_text_field](https://developer.wordpress.org/reference/functions/sanitize_text_field/)). It's also security issue because someone could try XSS attacks.

**Comment by f2ex** [comment]
@stodorovic hi, thank you very much!  It seems that you have solved the problem. Thank you for your suggestion, I also installed a firewall to prevent some XSS attacks .

My php version is 5.4 , wordpress version is 4.8.1 。I am sure that the problem you reproduce is the problem I have encountered .
