### ISSUE TITLE
wpcache_broken_message function breaks front-end AJAX

### ISSUE THREAD

**Issue by fastlinemedia** [Automattic/wp-super-cache#36]
The advanced-cache.php file contains a function called wpcache_broken_message that runs on every front-end request (via register_shutdown_function) when there is an issue with the WP Super Cache setup and outputs this HTML comment...

`<!-- WP Super Cache is installed but broken. The constant WPCACHEHOME must be set in the file wp-config.php and point at the WP Super Cache plugin directory. -->`

The problem is, when you're trying to make a front-end AJAX request (instead of using admin-ajax.php) that expects a JSON response, that comment breaks the script.

I have confirmed that this issue also breaks JSON responses from the [WP REST API](https://wordpress.org/plugins/json-rest-api/).

Thanks!
Justin

**Comment by kraftbj** [comment]
In your usage, are you seeing the `DOING_AJAX` constant to match how admin-ajax.php does it? In #37, I can ensure output doesn't occur for the common situations where this is breaking things (ajax, REST, XMLRPC).

I believe we're doing it this way versus tacking it on to a hook, since `advanced-cache.php` is loading before `wp-includes/plugin.php` which defines the `add_action`, etc hooks.

**Comment by fastlinemedia** [comment]
@kraftbj thanks for the quick follow up! #37 looks like it fixes the issue (we have DOING_AJAX defined). I look forward to that being merged in.
