### ISSUE TITLE
WP-CLI cron compatibility

### ISSUE THREAD

**Issue by AntonyXSI** [Automattic/wp-super-cache#440]
The WP Super Cache crons, wp_cache_gc_watcher and wp_cache_gc don't seem to be fired when using the cron feature through WP-CLI. 

I'm assuming this is because wp-cli bypasses advanced-cache.php and therefore won't load the cache-phase files that contain the cron jobs.

**Comment by stodorovic** [comment]
WPSC uses a lot of global variables. It could be source of this issue because WP-CLI handles _GLOBALS_ differently. You can look [WP-CLI #2289](https://github.com/wp-cli/wp-cli/issues/2289).

It's similar issue as #431. I'll try to make some improvements. I'm still testing some code and when I'm sure that works correctly, then I'll make new PR.
