### ISSUE TITLE
Plugin is caching www version of our homepage seperately

### ISSUE THREAD

**Issue by absolutelynotjames** [Automattic/wp-super-cache#455]
Hi,
We have wp-super-cache installed and working great for the most part. Our website does not use www in the url, However, very occasionally wp-super-cache will cache another copy of our homepage with the www. (so logged out users who type https://www will get this out of date cached version instead of being redirected to remove the www). I've noticed a second folder appear in the super cache directory for the www version of our url. (Deleting it seems to solve the problem). Is there any way we can prevent this from happening? I tried adding the https://www string of our url into the exclude urls area (doesn't break homepage caching but also doesn't resolve the issue).

I'm happy to provide any additional information if needed, thanks!

**Comment by donnchawp** [comment]
You can add a rewrite rule to your .htaccess file to fix this. I have this in mine:

RewriteCond %{HTTP_HOST} www.inphotos.org$ [NC]
RewriteRule ^(.*)$ https://inphotos.org/$1 [L,R=301]

(and because my server is misconfigured the rule doesn't work properly any more. It redirects to my main blog. I'll fix it eventually.)

**Comment by absolutelynotjames** [comment]
Thanks very much @donnchawp :)
