### ISSUE TITLE
WordPress 4.9 compatibility issues - unable to detect rewrite rules

### ISSUE THREAD

**Issue by Jon007** [Automattic/wp-super-cache#461]
After update to Wordpress 4.9, all sites report:
> Rewrite rules must be updated
> 
> The rewrite rules required by this plugin have changed or are missing. Scroll down the Advanced Settings page and click the Update Mod_Rewrite Rules button.
> 

Others possibly using simple caching are getting:
> Warning! Could not update /home/SITENAMEl/wp-config.php! 

see  https://wordpress.org/support/topic/super-cache-stopped-working-after-upgrade-to-4-9/

**Comment by donnchawp** [comment]
A [comment a couple of hours ago](https://wordpress.org/support/topic/super-cache-stopped-working-after-upgrade-to-4-9/#post-9700638) says the problem with rewrite rules is in WP 4.9 and will be fixed in 4.9.1.

**Comment by stodorovic** [comment]
First issue is related to https://wordpress.org/support/topic/rewrite-rules-must-be-updated-message-on-wordpress-4-9/ and it's fixed by https://core.trac.wordpress.org/ticket/42579. It's bug in WP core related to [extract_from_markers](https://developer.wordpress.org/reference/functions/extract_from_markers/).

Second issue is probably related to opcache (not directly related to WP update) and it's maybe fixed by PR #444. So, I think that they are two independent issues.

**Comment by Jon007** [comment]
it's a fair point, as it only happens with 4.9, it's a bug with 4.9 so perhaps I shouldn't have opened the issue here.   
Applying the fix from trac 42579 is successful so the issue can be closed here.
