### ISSUE TITLE
0 === $cachedata is never true

### ISSUE THREAD

**Issue by werther99** [Automattic/wp-super-cache#568]
PHP Version 7.1.9

This line `if ( 0 === $cachedata )` never evaluates as true. 
 
Doing: `write_log(gettype(0) . "-" . gettype($cachedata));` 

I get: `integer-string`

**Comment by donnchawp** [comment]
This is in plugins/dynamic-cache-test.php ?

**Comment by donnchawp** [comment]
The code is correct. It's possibly overly complicated and should probably have two functions to do this rather than rely on the $cachedata function.

The dynamic_output_buffer_init() function sets up an action on wp_footer to run dynamic_output_buffer_test with no parameters. That generates the "dynamic text" that refreshes on every load and stores it in "DYNAMIC_OB_TEXT". The same function is then called by the "wpsc_cachedata" action with the cached page in $cachedata and the first 3 lines of the function replaces the buffer tag with the dynamic text.
