### ISSUE TITLE
Site with multiple domains delete cache.

### ISSUE THREAD

**Issue by danieldudas** [Automattic/wp-super-cache#570]
We have a website that can be reached through multiple domains:
example.com
example.org
xmple.com
and so on. If I count them with and without www. then it's 28 total.
WP Super Cache stores the cache files separately for each domain, so if someone makes some changes on the site, to wipe all the cache someone would have to log in 28 times and delete the cache to be sure.
I was thinking about writing a plugin that would delete the Cache Location folder. Would it solve the problem?

**Comment by donnchawp** [comment]
It would, but I would write a plugin that deleted the folder for each website instead of the main cache directory. So delete wp-content/cache/supercache/example.com instead of deleting wp-content/cache/.

There's a .htaccess file in the cache directory, and possible index.html files in case you have "directory indexes" enabled on your server. And deleting exactly what you need to delete is safer than deleting everything in the cache directory.
