### ISSUE TITLE
get_sample_permalink undefined inside wpsc_post_transition

### ISSUE THREAD

**Issue by Logicbloke** [Automattic/wp-super-cache#594]
Hi,

I'm using a theme called PricerrTheme which is basically a Fiverr clone. Users can add new services but they must be approved by an admin. So naturally services are added as a draft and then published by an admin.

The problem is, I have been getting a fatal error on get_sample_permalink at wp-cache-phase2.php inside wpsc_post_transition. Basically triggered when a post changes its status from draft to publish or the opposite. Normally the posts aren't published, they're just being created as drafts so I'm not sure why WP Super Cache is getting involved at this point. Maybe the theme is creating the services as published and then changing their status to draft right away, getting WP Super Cache involved in the way.

I understand that this is to delete old URLs from cache and hindering them from being served but can't we disable this auto-purge and just rely on the scheduler?

The major question here is why get_sample_permalink is undefined in wp-cache-phase2.php:2721 (function wpsc_post_transition).

```
PHP Fatal error:  Uncaught Error: Call to undefined function get_sample_permalink() in /wordpress/wp-content/plugins/wp-super-cache/wp-cache-phase2.php:2721
Stack trace:
#0 /wordpress/wp-includes/class-wp-hook.php(286): wpsc_post_transition('draft', 'publish', Object(WP_Post))
#1 /wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /wordpress/wp-includes/post.php(4128): do_action('transition_post...', 'draft', 'publish', Object(WP_Post))
#4 /wordpress/wp-includes/post.php(3588): wp_transition_post_status('draft', 'publish', Object(WP_Post))
#5 /wordpress/wp-includes/post.php(3746): wp_insert_post(Array, false)
#6 /wordpress/wp-content/themes/pricerrtheme/lib/post_new_post.php(372): wp_update_post(Array)
```

I'm using **Wordpress 4.9.8** and **WP Super Cache 1.6.3**. Any ideas?

Thank you,

**Comment by stodorovic** [comment]
I will try to create PR which fixes it tomorrow.

**Comment by stodorovic** [comment]
Thanks for reporting this issue. I was able to reproduce this.

I just created #595 which fixes this issue. It loads [PHP file](https://github.com/WordPress/WordPress/blob/4.9.8/wp-admin/includes/post.php#L1216-L1292) where [`get_sample_permalink`](https://codex.wordpress.org/Function_Reference/get_sample_permalink) is located if this function doesn't exist. We can't avoid [`get_sample_permalink`](https://codex.wordpress.org/Function_Reference/get_sample_permalink) because it's regular way to find previous URL when post is unpublished. I've tested it couple months ago and I didn't find issues related to WP post editor.

I'd guess that some plugins/themes use functions [wp_insert_post](https://codex.wordpress.org/Plugin_API/Action_Reference/wp_insert_post), [wp_publish_post](https://codex.wordpress.org/Function_Reference/wp_publish_post) or [wp_update_post](https://codex.wordpress.org/Function_Reference/wp_update_post) in frontend when _wp-admin_ functions aren't loaded. I don't have PricerrTheme, but I've created PHP script which reproduces this behavior:
```
<?php

// Set _SERVER vars
include_once( 'wp-cli-parameters.php' );

// load wp scripts
include_once( __DIR__.'/../public_html/wp-load.php' );

// Insert post.
$my_post = array();
$my_post['post_title'] = 'Test post';
$my_post['post_content'] = "It's simple post.";
$my_post['post_status'] = 'auto-draft';
$my_post_id = wp_insert_post( $my_post );

// Publish post.
wp_publish_post( $my_post_id );

// Set again to draft.
$my_post['filter'] = 'sample';
$my_post['post_status'] = 'draft';
$my_post['ID'] = $my_post_id;
wp_update_post( $my_post );
```

It would be great if you could test #595.

**Comment by Logicbloke** [comment]
Thank you very much, #595 did the trick!
