### ISSUE TITLE
Do not update config file if setting value has not changed

### ISSUE THREAD

**Issue by donnchawp** [Automattic/wp-super-cache#648]
The function wp_cache_setting() and wp_cache_replace_line() do not check if the value of the setting being updated has changed since being written to the configuration file. This may result in needless updates to that file, which in some circumstances (#646) may cause corruption.

The plugin should check if the value has changed but this has it's own challenges.

The configuration file is a PHP file, and will be compiled by PHP. Changes to the file will not be detected until the next request to the webserver. This was noted during the development of the REST API when updates to that file weren't seen when the file was loaded again using include(). The command [opcache_invalidate() had to be used](https://github.com/Automattic/wp-super-cache/blob/4947a3d892765993de4ac3980caba5d39ca36a1b/rest/class.wp-super-cache-rest-get-settings.php#L25) to refresh it. That has a performance penalty and some hosts don't like it.

However that penalty might be worth it given that the alternative is corruption of the configuration file if some other plugin is misbehaving and updating it on every request.

I think we could do this by modifying wp_cache_setting(). It would opcache_invalidate() the configuration file and include it, loading the variables into the scope of the function, then check if the setting has changed. This might be expensive to do if there are multiple calls to the function, so those calls might have to be queued together.

Alternatively, we could do this if all the settings were in an array, or if there was an array of settings variables. When the file is loaded the plugin makes a backup of the settings. The next time wp_cache_setting() is called it would check the value in that backup list before deciding to update or not. If changed the backup list value has to be updated too, just in case the value is changed back before the end of the request.

**Comment by DrLightman** [comment]
Please note, regarding my issue in the closed issue, the corruption was dued to many subsequent writes over the the config file. There were 2 consecutives cookie add -> cookie remove at each page load and it ended up at some point in the corruption.

Judging from the wpsc code, a cookie which is already there in the config, won't trigger the rewrite of the file. Same goes if a plugin want to remove cookie and the cookie is already not there.

```php
function wpsc_add_cookie( $name ) {
	global $wpsc_cookies;
	if (
		! isset( $wpsc_cookies ) ||
		! is_array( $wpsc_cookies ) ||
		! in_array( $name, $wpsc_cookies )
	) {
		$wpsc_cookies[] = $name;
		wp_cache_setting( 'wpsc_cookies', $wpsc_cookies );
	}
	return $name;
}
add_action( 'wpsc_add_cookie', 'wpsc_add_cookie' );

function wpsc_delete_cookie( $name ) {
	global $wpsc_cookies;
	if (
		isset( $wpsc_cookies ) &&
		is_array( $wpsc_cookies ) &&
		in_array( $name, $wpsc_cookies )
	) {
		unset( $wpsc_cookies[ array_search( $name, $wpsc_cookies ) ] );
		wp_cache_setting( 'wpsc_cookies', $wpsc_cookies );
	}
	return $name;
}
add_action( 'wpsc_delete_cookie', 'wpsc_delete_cookie' );
```

The `wp_cache_setting` settign there always trigger a file wirte if I'm not mistaken.

The problem was that I removed it and after that the plugin readded after few milliseconds. This at every page load.

a - Plugin side, the fix would have been to perform the check/add only on activation hook maybe.

b - WPSC side, a fix would be to implement same sort of semaphore in the config write process, so that you can safely write the config only when no other write has finished yet. With the risk of causing some app hang here maybe.

**Comment by donnchawp** [comment]
@DrLightman - you're right. The cookies array shouldn't have been modified on every load of the cookie notice plugin because it was adding the same cookie (cookie_notice_accepted) each time.

> The problem was that I removed it and after that the third party plugin readded after few milliseconds. This at every page load.

You mean you removed the cookie_notice_accepted cookie from the list? And then the cookie_notice plugin tried to add it again immediately? So, there was only one instance of corruption, the first time it needed to be added?

I was going to make the wp_cache_replace_line function write to a temporary file first because of this type of issue but I can see it's still required. I'll do that as a fix for this.

**Comment by DrLightman** [comment]
> You mean you removed the cookie_notice_accepted cookie from the list? And then the cookie_notice plugin tried to add it again immediately? So, there was only one instance of corruption, the first time it needed to be added?

Yes, because I wanted the wp super cache files instead of the php ones, so I try to keep the custom cookies list empty... anyway, my setup is a bit tweaked, this is what I want in my site.

So I added an action to remove the cookie before of 'init'. But the third party plugin (Cookie Notice) has an action on 'init' that adds the cookie again... so there was this infinte mechanism of adding/removing/adding/removing/... at each page load.

> I was going to make the wp_cache_replace_line function write to a temporary file first because of this type of issue but I can see it's still required. I'll do that as a fix for this.

It should work, as long as the action of renaming the temp file to the real config file doesn't cause conflicts.

**Comment by donnchawp** [comment]
On Unix systems at least renaming a file is atomic so in the worse case, two processes update the cookie list at the same time.

In #652 I changed the update script so it uses a tempoary file, but also that it does not update the config file if the setting hasn't changed which might help here when multiple writers load the config file within a short time. Hopefully the first 1 or 2 will try to update, but others will see the change and stop.
