### ISSUE TITLE
Slowness when saving the home page

### ISSUE THREAD

**Issue by mackensen** [Automattic/wp-super-cache#654]
We're seeing behavior on a multisite where saving the home page, when there are a large number of supercached files, takes a long time, to the point where gateway timeouts occur. This feels similar to #98, but I don't think the plugin is trying to prune the cache.

* WP Super Cache version: 1.6.4
* WordPress version: 4.9.9
* Clear all cache files when a post or page is published or updated: disabled
* Preload mode: enabled

We store the cache files on a GlusterFS system that's not the fastest in the world; if there's some kind of repeated directory traversal taking place that could explain what we're seeing. We're considering better file storage options. In the interim, we've founding that manually deleting the cache eliminates the issue.

**Comment by donnchawp** [comment]
> We store the cache files on a GlusterFS system that's not the fastest in the world

Unfortunately that's the problem. It's recommended that cached files be stored in a local directory. If you have a multi server set up I would recommend something like [Batcache](https://github.com/Automattic/batcache) which is what is used on WordPress.com.

Otherwise, you should probably disable preload mode and reduce the cache timeout time so there are fewer cache files.

**Comment by mackensen** [comment]
Thanks @donnchawp; we'll give that a shot. We've looked at Batcache before, but I think we were single-node at the time.
