### ISSUE TITLE
Is my site compromised?

### ISSUE THREAD

**Issue by jasulainen** [Automattic/wp-super-cache#655]
I've site www.qkaasu.com

Last night I got a warning from malicious software detection tool. 

File that this is about:
`/wp-content/cache/supercache/www.qkaasu.com/meta-wp-cache-fed01d9743efb18193dcd97a5d244ee0.php`

`<?php die(); ?>{"headers":{"Vary":"Vary: Accept-Encoding, Cookie","Content-Encoding":"Content-Encoding: gzip","Content-Type":"Content-Type: text\/html; charset=UTF-8","Link":"Link: <https:\/\/www.qkaasu.com\/wp-json\/>; rel=\"https:\/\/api.w.org\/\"","Content-Length":"Content-Length: 7035","Last-Modified":"Last-Modified: Wed, 06 Mar 2019 04:16:43 GMT"},"uri":"www.qkaasu.com\/?s=my\/show\/id\/%7B~eval$_POST[qazw]%7D","blog_id":1,"post":0,"key":"www.qkaasu.com80\/?s=my\/show\/id\/%7B~eval($_POST[qazw])%7Dgzip"}
`
Those evals causes the alert. But can those be actually executed? 

I've just updated all plugins etc yesterday, so i was running newest version.

**Comment by donnchawp** [comment]
@jasulainen - Yikes it might be. WP Super Cache is just caching the page as it sees it from WordPress.

Maybe search through your site for "qazw" or "eval" and see if anything shows up? You could also try the [Exploit Scanner](https://wordpress.org/plugins/exploit-scanner/) plugin, but it'll probably show lots of false positives as it hasn't been updated in quite a while.

**Comment by donnchawp** [comment]
Hang on. I see what's going on here. Ignore my previous comment. That's a cached search page. Someone was testing an exploit on your site. They can't exploit the cached version because POST requests aren't served from the cache.

So, even though they might visit that same search page with the eval bits and POST to it, the plugin won't use the cached page to serve that page.

I don't think it's anything to worry about.

**Comment by jasulainen** [comment]
Thanks a lot! It seemed fishy but i was also uncertain what it means when cached file starts with <?php die(); ?>
