### ISSUE TITLE
undefined function wpsc_deep_replace()

### ISSUE THREAD

**Issue by Helmi** [Automattic/wp-super-cache#75]
When trying to save advanced settings this happens:

[Fri Nov 06 12:27:31 2015] [error] [client 1.2.3.4] PHP Fatal error:  Call to undefined function wpsc_deep_replace() in /var/www/user/data/www/userdomain.com/wp-content/plugins/wp-super-cache/wp-cache.php on line 502, referer: http://userdomain.com/wp-admin/network/settings.php?page=wpsupercache&tab=settings

Known problem? Solutions?

**Comment by rjksn** [comment]
Has there been any response to this? Do we even know what it's supposed to do?

    Fatal error: Call to undefined function wpsc_deep_replace() in …plugins/wp-super-cache/wp-cache.php on line 502

**Comment by ragtech** [comment]
Same here and the error has been reported here as well https://wordpress.org/support/plugin/wp-super-cache

Hoping for a fix or possible work-around.

Thanks

**Comment by seocam** [comment]
Same problem here.

**Comment by noelboss** [comment]
Same here

**Comment by bozzmedia** [comment]
Also similar issue here. Reported along with other recurring php notices here: https://wordpress.org/support/topic/php-fatal-error-on-delete-cache-settings-pages

**Comment by wiledal** [comment]
This problem usually happens if the cache plugin is enabled, but the `advanced-cache.php` inclusion is actually not running. This can easily happen when running custom WP implementations such as [Bedrock](https://roots.io/bedrock/) (which was the problem I was having).

To verify what is broken, look into your plugins and click on the `drop-ins`-tab. If it's "Inactive", then that's your problem.

![Plugins](http://i.imgur.com/BAmMDFJ.jpg)

I believe it is caused when WPSC cannot edit the `wp-config.php`, and therefore `WP_CACHE` is never defined as `true` which in turn causes it to never include the `advanced-cache.php`.

I solved it by adding this to my config file:
```php
define('WP_CACHE', true);
define('WPCACHEHOME', __DIR__ . '/../web/app/plugins/wp-super-cache/');
```
This is specific for Bedrock, and you might need to set `WPCACHEHOME` to correspond to your setup.

**Comment by bozzmedia** [comment]
Fine work, wiledal. Seems this dependency should be checked and error message presented to the user about the failure to write to wp-config and to manually edit the file.

**Comment by wanderinguy** [comment]
Can I just say - THANK YOU THANK YOU THANK YOU. - This is the only place dealing with this question that offered me any help with this issue.

   I wrestled with WP Super Cache Settings for a few hours trying to figure out this problem

Fatal error: Call to undefined function wpsc_deep_replace() in .../public_html/wp-content/plugins/wp-super-cache/wp-cache.php on line 533

and I typed in your code exactly as above

define( 'WP_CACHE', true );
/*Ok this next line is because the cache plugin is enabled, but the advanced-cache.php inclusion is actually not running. To verify what is broken, look into your plugins and click on the drop-ins-tab. If it's "Inactive", then that's your problem.  WPSC cannot edit the wp-config.php, and therefore WP_CACHE is never defined as true which in turn causes it to never include the advanced-cache.php.  */

define('WPCACHEHOME', __DIR__ . '/../web/app/plugins/wp-super-cache/');


AND VIOLA - 
It worked perfectly.

And to backup- here was the problem I was trying to solve with WP Super Cache

NOTICE
A temporary block has been placed on database access by your user account ********* on stealth. The database associated with /home/*******/public_html was consuming excessive server resources and degrading overall system performance. While we limit each account to 25% of the servers CPU, as described in our terms of service, we only disable accounts if they greatly exceed this level and begin to affect other users on the server. We have provided more information about the recent site activity at the end of this ticket.

So without any warning (And by the way the HD and bandwidth usage were only half used) 
Hostgator just shut my site down. Everyone should take this as a big warning. Host Gator will shut you down, when you haven't done anything wrong- but that somebody on your site used up a lot of their CPU.

Their response (after waiting 2.5 hours) was:
Unfortunately it would not have been possible to send a warning notification in regards to the CPU usage in question. This is primarily due to the fact that the reported CPU usage would not have been apparent until it had already started negatively affecting the integrity of the shared hosting environment. Please understand that shared hosting plan are limited to 25% of any given resource on the server, including CPU usage. This can be reviewed in in both our Acceptable Use Policy and our Terms of Service. 

After repairing it I sent of a request to be reinstated. --- That was over an hour and a half ago ...........

**Comment by wanderinguy** [comment]
Without any warning Hostgator shut us down (apparently many hosts out there do the same unless you have a $100/month dedicated IP address.) It seems very unfair that - what happened by bad guys (DDoS attack), at a moments notice, shut us down. By the next day I had everything running smoothly again (Thanks to wiledal) . It still took the hosting company Hostgator- 2 more days to restore our access, meaning our site was down for 3 days.
